### ISSUE TITLE
is it useable for android?

### ISSUE THREAD

**Issue by MatejMagat305** [MarinX/goble#1]
Hi I m coding in https://github.com/fyne-io/fyne, and it can run on android, it this library suitable for android?

**Comment by MarinX** [comment]
Hey @MatejMagat305 ,
This library is not suitable for android because it uses a low level read/write from serial port.
This requires a root permission on android.

If you are looking to call bluetooth stuff on go, the best way is to find gomobile bindings for android bluetooth API or build your own where you will call Java(Android) API from Go
